[greeter]
background=/usr/share/backgrounds/gradient-linux/gradient-canvas-wallpaper.svg
theme-name=Adwaita
icon-theme-name=Papirus
font-name=IBM Plex Sans 11
xft-antialias=true
xft-dpi=110
clock-format=%A, %d %B %Y  %H:%M
indicators=~host;~spacer;~clock;~session;~a11y;~language;~power
